version: '3.9'

services:
  framework-dev:
    image: framework-dev
    container_name: framework-dev
    stdin_open: false # for the -i flag
    tty: false # for -t flag
    cpus: 2
    mem_limit: 1g
    

    ports:
      - "6969:6969"

    volumes:
      - .:/app # volume or directory to mount

    working_dir: /app

    command: sh -c "make && ./server"
